#!/bin/bash

if ! [[ -d "aoba-engine/aoba-core/asm/aoba/core/system/" ]]; then
  echo "Error: Script must be executed from project root."
  exit 1
fi

FILE=aoba-engine/aoba-core/asm/aoba/core/system/generated_tables.fma
echo "; Generated by $0" > $FILE

for command in tools/codegen/*; do
  node $command >> $FILE
done
